name: Build Passport Client

on:
  release:
    types:
      - created

jobs:
  build-passport-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set environment variables
        id: vars
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
          echo ::set-output name=releaseDate::$(date -u +"%FT%T.000Z")
      - name: Build the Docker image
        working-directory: ./services/passport-client
        run: docker build . --file Dockerfile-prod --tag sublayer/passport-api:${{ steps.vars.outputs.tag }}
      - name: Login into Gitlab Docker Registry
        run: docker login -u sublayer -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Gitlab Docker Registry
        run: docker push sublayer/passport-api:${{ steps.vars.outputs.tag }}
